% Anonymous function
% f=@(arglist)expression
f = @(x); % change
x0 = [];
options = optimoptions('fminunc', ...
 'SpecifyObjectiveGradient', true, ...
 'Algorithm', 'quasi-newton', ...
 'TolX', 1e-12, ...
 'TolFun', 1e-12, ...
 'Display', 'iter');
[x, fval, exitflag, output] = fminunc(f, x0, options)