x0 = [1, 1];

options = optimoptions('fminunc', ...
 'SpecifyObjectiveGradient', true, ...
 'Algorithm', 'quasi-newton', ...
 'TolX', 1e-12, ...
 'TolFun', 1e-12, ...
 'Display', 'iter');

[x, val, exitflag, output] = fminunc(@zad2_fun, x0, options) %#ok<NOPTS>